#  # creation and accessing the elements of an array

In [54]:
from numpy import *
arr=array([[1,5,3,8],[4,8,3,9]])
print(arr)
print(arr[0][3],arr[1][2])

[[1 5 3 8]
 [4 8 3 9]]
8 3


# # changing datatype 

In [25]:


from numpy import *
arr=array([[1,5,3,8],[4,8,3,9]])
print(arr)
print(arr[0][3],arr[1][2])

[['1' '5' '3' '8']
 ['4' '8' '3' '9']]
8 3


# # dimensions of array

In [32]:


from numpy import *
arr=array([[1,5,3,8]])
print(arr.ndim)

2


# # size and type of each element

In [36]:

arr=array([[1,5,3,8],[4,8,3,9]])
print(arr.itemsize)
print(arr.dtype)


4
int32


# # shape and size and reshaping of array

In [40]:
arr=array([[1,5,3,8],[4,8,3,9]])
print(arr.shape)
print(arr.size)
print(arr.reshape(4,2))

(2, 4)
8
[[1 5]
 [3 8]
 [4 8]
 [3 9]]


# # linspace --returns divided range

In [41]:
print(linspace(1,15,10))

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]


# # max,min and sum functions

In [44]:
arr=array([2,6,4,9,7])
print(max(arr))
print(min(arr))
print(sum(arr))

9
2
28


# # numpy array axis

In [50]:
arr=array([[1,5,3,8],[4,8,3,9]])
print(arr.sum(axis=0))
print(arr.max(axis=1))
print(arr.min(axis=0))

[ 5 13  6 17]
[8 9]
[1 5 3 8]


# # square root and standard deviation

In [53]:
arr=array([[1,5,3,8],[4,8,3,9]])
print(sqrt(arr))
print(std(arr))

[[1.         2.23606798 1.73205081 2.82842712]
 [2.         2.82842712 1.73205081 3.        ]]
2.7128168017763383


# # array arithmatic operations


In [59]:
a=array([[2,5,4,6,7],[4,6,7,3,1]])
b=array([[4,7,1,4,5],[5,6,8,1,3]])
print(a+b,end=" ")
print(a*b,end=" ")
print(a/b,end=" ")
print(a-b,end=" ")

[[ 6 12  5 10 12]
 [ 9 12 15  4  4]] [[ 8 35  4 24 35]
 [20 36 56  3  3]] [[0.5        0.71428571 4.         1.5        1.4       ]
 [0.8        1.         0.875      3.         0.33333333]] [[-2 -2  3  2  2]
 [-1  0 -1  2 -2]] 

# # array concatenation

In [67]:
from numpy import *
a=array([[2,5,4,6,7],[4,6,7,3,1]])
b=array([[4,7,1,4,5],[5,6,8,1,3]])
print(hstack(a))
print(vstack(a))

[2 5 4 6 7 4 6 7 3 1]
[[2 5 4 6 7]
 [4 6 7 3 1]]


# # creation of an empty array

In [71]:
from numpy import *
a=empty((3,2),dtype=int)
print(a)

[[         0          0]
 [         0          0]
 [         0 1072693248]]


# # creation of ones array

In [72]:
from numpy import *
a=ones((3,4),dtype="float")
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# # creation of a zeroes array

In [77]:
from numpy import *
a=zeros((5,6),dtype=int)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


# #array from existing data

# numpy.asarray

In [81]:
lis=[3,7,5,9,1,'4']
print(asarray(lis,int))

[3 7 5 9 1 4]


In [82]:
tup=(7,8,3,6,1,9)
print(asarray(tup,float))

[7. 8. 3. 6. 1. 9.]


# # numpy.frombuffer(buffer,dtype)---array from existing buffer

# numpy.frombuffer

In [85]:
l=b"hello world!"
a=frombuffer(l,int)
print(a)

[1819043176 1870078063  560229490]


# numpy.fromiter()

In [95]:
from numpy import *
it=[3,6,1,7]
a=fromiter(it,float)
print(a)

[3. 6. 1. 7.]


# # numpy bitwise operators

In [7]:
from numpy import *
a=10
b=12

print(bin(a))
print(bin(b))
print(bitwise_and(a,b))
print(bitwise_or(a,b))
print(invert(a))

0b1010
0b1100
8
14
-11


In [12]:
a=array([[3,5,1,6],[4,7,1,4]])
b=array([[3,6,2,8],[8,1,6,3]])
print(bitwise_and(a,b))
print(bitwise_or(a,b))
print(invert(a))
print(left_shift(a,2))

[[3 4 0 0]
 [0 1 0 0]]
[[ 3  7  3 14]
 [12  7  7  7]]
[[-4 -6 -2 -7]
 [-5 -8 -2 -5]]
[[12 20  4 24]
 [16 28  4 16]]



# # NUMPY STRING FUNCTIONS


# 1. add()

In [2]:
from numpy import *
char.add(['welcome','hi'],['to java','read'])

array(['welcometo java', 'hiread'], dtype='<U14')

# 2. multiply()

In [3]:
char.multiply("hi",3)

array('hihihi', dtype='<U6')

# 3. center()

In [4]:
char.center("vikash",23,"-")

array('---------vikash--------', dtype='<U23')

# 4. capitalize()

In [5]:
char.capitalize("hkdfhgugdsjkdsfkkgsdk")

array('Hkdfhgugdsjkdsfkkgsdk', dtype='<U21')

# 5. title() 

In [6]:
char.title("hey you fuck off ")

array('Hey You Fuck Off ', dtype='<U17')

# 6. lower()

In [7]:
char.lower("VIKASHARMA")

array('vikasharma', dtype='<U10')

# 7.upper()

In [8]:
char.upper("sumit kutta")

array('SUMIT KUTTA', dtype='<U11')

# 8. split()

In [10]:
char.split("vikash sharma the legend")

array(list(['vikash', 'sharma', 'the', 'legend']), dtype=object)

# 9. strip()

In [11]:
char.strip("           vikash        ")

array('vikash', dtype='<U25')

# 10. join()

In [12]:
char.join(":",'vikash sharma')

array('v:i:k:a:s:h: :s:h:a:r:m:a', dtype='<U25')

# 11. replace()

In [14]:
s=" the name of the taj was the taj"
s.replace("the","something")

' something name of something taj was something taj'

# # LOGIRITHMICS FUNCTIONS 

# 1. log--base e

In [16]:
from numpy import *
log(16)

2.772588722239781

# 2. log-- base 2

In [17]:
log2(8)

3.0

# 3. log--base 10

In [18]:
log10(1000)

3.0

#  # TRIGNOMETRIC FUNCTIONS

# 1. sin()

In [26]:
sin(pi/4)

0.7071067811865476

# 2. asin()

In [28]:
asin(1)

NameError: name 'asin' is not defined

# # DEGREES AND RADIANS

# 1. rad2deg()

In [33]:
a = array([pi,2*pi])
rad2deg(a)


array([180., 360.])

# 2. deg2rad()

In [32]:
a = array([0,90, 180, 270])
deg2rad(a)

array([0.        , 1.57079633, 3.14159265, 4.71238898])